name: Build and Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  VERSION: '1.0.3'

jobs:
  build:
    name: Build TrollInstallerX
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          submodules: true

      - name: Pre theos
        run: |
         curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos > theos
         sed -i '' 's/get_sdks$//g' theos
         bash theos

      - name: Setup Environment
        run: echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Build ipa
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: TrollInstallerX_${{ env.VERSION }}
          path: TrollInstallerX.ipa